name = "Shadow Journal"
license = "MIT"
description = "Un thème nocturne et introspectif pour journal intime avec une esthétique mystérieuse et profonde"
homepage = ""
tags = ["blog", "journal", "dark", "minimal", "personal"]
features = ["dark-mode", "elegant", "typography", "introspective"]
min_version = "0.80.0"

[author]
  name = "Claude Code"
  homepage = ""